// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/2/2025, 2:35:01 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/plugins/**/*.{js,ts,mjs}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/composables/**/*.{js,ts,mjs}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/utils/**/*.{js,ts,mjs}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/liuyinjiwen/Documents/0-Addsubtitle/Codes/srt to vtt2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;